name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install curl build-essential python3-pip
      - name: Install PlatformIO
        run: sudo -H pip3 install platformio
      - name: Build with PlatformIO
        run: make all
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: firmware.elf
          path: .pio/build/esp32/firmware.elf
      - name: Upload release asset
        if: github.event_name == 'release' && (github.event.action == 'published' || github.event.action == 'created')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: .pio/build/esp32/firmware.elf
          asset_name: firmware.zip
          asset_content_type: application/zip